# Generated by Django 3.1.2 on 2022-04-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220411_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente_fonoaudiologia',
            options={'verbose_name': 'Paciente fonoaudiologia', 'verbose_name_plural': 'Pacientes fonoaudiologia'},
        ),
    ]
