# Generated by Django 3.1.2 on 2022-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220411_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente_fonoaudiologia',
            name='audio_wav',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente_fonoaudiologia',
            name='video',
            field=models.CharField(max_length=50),
        ),
    ]
