# Generated by Django 3.1.2 on 2022-04-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220411_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente_fonoaudiologia',
            name='rut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.paciente'),
            preserve_default=False,
        ),
    ]
